# -*- coding: utf-8 -*-
"""tradutor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OT4Gledunve_W3QMUV3-V9j_gtJND-Ik
"""

import requests
from bs4 import BeautifulSoup

def extract_text_from_url(url):
  response = requests.get(url)

  if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')
    for script_or_style in soup(['script', 'style']):
      script_or_style.decompose()
    texto = soup.get_text(separator=' ')
    linhas = (line.strip() for line in texto.splitlines())
    parts = (phrase.strip() for line in linhas for phrase in line.split("  "))
    texto_limpo = '\n'.join(part for part in parts if part)
    return texto_limpo
  else:
    print(f"Failed to fetch the URL. Status code: {response.status_code}")
  text = soup.get_text()
  return text

extract_text_from_url('https://dev.to/kenakamu/azure-open-ai-in-vnet-3alo')

from langchain_openai.chat_models.azure import AzureChatOpenAI

client = AzureChatOpenAI(
    azure_endpoint = "[ENDPOINT]",
    api_key = "[API KEY]",
    api_version ="[VERSION]",
    deployment_name = "gpt-4o-mini",
    max_retries = 0
)

def translate_article(text, lang):
  messages = [
      ("system", "Você atua como tradutor de textos"),
      ("user", f"Traduza o {text} para o idioma {lang} e responda em markdown")
  ]
